---
AWSTemplateFormatVersion: '2010-09-09'
Description: Cloudformation template to create all roles
Resources:
  InstanceRole:
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "ec2.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Policies:
        -
          PolicyName: "InstanceRole"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action: 
                  - "sqs:*"
                  - "s3:*"
                Resource: "*"
  InstanceProfile: 
    Type: "AWS::IAM::InstanceProfile"
    Properties: 
      Roles: 
        - 
          Ref: "InstanceRole"
Outputs:
  InstanceRole:
    Value: !GetAtt 'InstanceRole.Arn'
    Description: InstanceRole arn
    Export: 
      Name: !Sub "${AWS::StackName}-InstanceRole"
  InstanceProfile:
    Value: !GetAtt 'InstanceProfile.Arn'
    Description: InstanceProfile arn
    Export: 
      Name: !Sub "${AWS::StackName}-InstanceProfile"
  StackName:
    Value: !Ref AWS::StackName


